# Site settings
title: Iran University of Science and Technology
course_name: Software Engineering
course_description:
    The purpose of this tutorial is set to engineering tips that are available in all software designs. in this
    Lesson of starting a product difference that can be engineered with a resource that can provide you with gifts
    It will be explained later that you meet the expectations you have of a virtual engineering resource.
    Emphasis on engineering methods can be derived from modeling, validation and evaluation of law, implementation and
    Validation of Intermediate Products, Review of Scientific Instrumentation in All Software Training Programs
    This can be done by noting that in previous courses, students have formalized the needs, magnification,
    Estimates and known abilities in this lesson can be obtained using.
course_semester: "Fall 2020"
description: |
    Instructor: Dr. Behrouz Minaei Bidgoli

message: #Please register to our Google <a href="https://groups.google.com/forum/#!forum/gp-id">groups page</a> to get course notifications via email.
baseurl: "/SE98" # the subpath of your site, e.g. /blog/
url: "http://sauleh.github.io/course_template" # the base hostname & protocol for your site
syllabus: 
githubdir: 

# Author/user information
email: b_minaei@iust.ac.ir
address: |
    School of Computer Engineering
    Iran University of Science and Technology
    Tehran, Iran


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false

sass:
    style: :compressed        

defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
      comments: false



plugins:
    - jekyll-jalali
